CREATE TABLE IF NOT EXISTS public.all_hgv (
AADFYear INTEGER NOT NULL,
LocalAuthority VARCHAR(256) NOT NULL,
Region VARCHAR(256) NOT NULL,
Road VARCHAR(256) NOT NULL,
AverageAADF_AllHGV NUMERIC(18,2) NOT NULL,
AverageMiles_Driven_AllHGV NUMERIC(18,2) NOT NULL)
DISTSTYLE ALL;

CREATE TABLE IF NOT EXISTS public.ahgv ( 
AADFYear INTEGER NOT NULL,
LocalAuthority VARCHAR(256) NOT NULL,
Region VARCHAR(256) NOT NULL,
Road VARCHAR(256) NOT NULL,
AverageAADF_HGVA34 NUMERIC(18,2) NOT NULL,
AverageAADF_HGVR5 NUMERIC(18,2) NOT NULL,
AverageAADF_HGVR6 NUMERIC(18,2) NOT NULL,
AverageMiles_Driven_HGVR34 NUMERIC(18,2) NOT NULL,
AverageMiles_Driven_HGVR5 NUMERIC(18,2) NOT NULL,
AverageMiles_Driven_HGVR6 NUMERIC(18,2) NOT NULL)
DISTSTYLE ALL;

CREATE TABLE IF NOT EXISTS public.rhgv (
AADFYear INTEGER NOT NULL,
LocalAuthority VARCHAR(256) NOT NULL,
Region VARCHAR(256) NOT NULL,
Road VARCHAR(256) NOT NULL,
AverageAADF_HGVR2 NUMERIC(18,2) NOT NULL,
AverageAADF_HGVR3 NUMERIC(18,2) NOT NULL,
AverageAADF_HGVR45 NUMERIC(18,2) NOT NULL,
AverageMiles_Driven_HGVR2 NUMERIC(18,2) NOT NULL,
AverageMiles_Driven_HGVR3 NUMERIC(18,2) NOT NULL,
AverageMiles_Driven_HGVR45 NUMERIC(18,2) NOT NULL)
DISTSTYLE ALL;

CREATE TABLE IF NOT EXISTS public.all_motorvehicles (
AADFYear INTEGER NOT NULL,
LocalAuthority VARCHAR(256) NOT NULL,
Region VARCHAR(256) NOT NULL,
Road VARCHAR(256) NOT NULL,
AverageAADF_AMV NUMERIC(18,2) NOT NULL,
AverageMiles_Driven_AMV NUMERIC(18,2) NOT NULL)
DISTSTYLE ALL;

CREATE TABLE IF NOT EXISTS public.motor_vehicles (
AADFYear INTEGER NOT NULL,
LocalAuthority VARCHAR(256) NOT NULL,
Region VARCHAR(256) NOT NULL,
Road VARCHAR(256) NOT NULL,
AverageAADF_MC NUMERIC(18,2) NOT NULL,
AverageAADF_CT NUMERIC(18,2) NOT NULL,
AverageAADF_BC NUMERIC(18,2) NOT NULL,
AverageAADF_LV NUMERIC(18,2) NOT NULL,
AverageMiles_Driven_MC NUMERIC(18,2) NOT NULL,
AverageMiles_Driven_CT NUMERIC(18,2) NOT NULL,
AverageMiles_Driven_BC NUMERIC(18,2) NOT NULL,
AverageMiles_Driven_LV NUMERIC(18,2) NOT NULL)
DISTSTYLE ALL;

CREATE TABLE IF NOT EXISTS public.pedal_cycle (
AADFYear INTEGER NOT NULL,
LocalAuthority VARCHAR(256) NOT NULL,
Region VARCHAR(256) NOT NULL,
Road VARCHAR(256) NOT NULL,
AverageAADF_PC NUMERIC(18,2) NOT NULL,
AverageMiles_Driven_PC NUMERIC(18,2) NOT NULL)
DISTSTYLE ALL;

CREATE TABLE IF NOT EXISTS public.road (
Road VARCHAR(256) NOT NULL,
RoadCategory VARCHAR(256) NOT NULL,
Road_Grades VARCHAR(256) NOT NULL,
CONSTRAINT road_pkey PRIMARY KEY(Road))
DISTSTYLE ALL;


CREATE TABLE IF NOT EXISTS public.location ( 
Accident_Index VARCHAR(256) NOT NULL,
Location_Easting_OSGR INTEGER NOT NULL,
Location_Northing_OSGR INTEGER NOT NULL,
Longitude NUMERIC(18,2) NOT NULL,
Latitude NUMERIC(18,2) NOT NULL,
CONSTRAINT location_pkey PRIMARY KEY(Accident_Index))
DISTSTYLE ALL;

CREATE TABLE IF NOT EXISTS public.pedestrian (
Pedestrian_Index INTEGER NOT NULL,
Pedestrian_Crossing_Human_Control VARCHAR(256) NOT NULL,
Pedestrian_Crossing_Physical_Facilities VARCHAR(256) NOT NULL,
CONSTRAINT pedestrian_pkey PRIMARY KEY(Pedestrian_Index))
DISTSTYLE ALL;

CREATE TABLE IF NOT EXISTS public.road_table (
Road_Index INTEGER NOT NULL,
first_Road_Class INTEGER NOT NULL,
Road_Type VARCHAR(256) NOT NULL,
second_Road_Class INTEGER NOT NULL,
CONSTRAINT road_table_pkey PRIMARY KEY(Road_Index))
DISTSTYLE ALL;

CREATE TABLE IF NOT EXISTS public.condition (
Condition_Index VARCHAR(256) NOT NULL,
Weather_Conditions VARCHAR(256) NOT NULL,
Light_Conditions VARCHAR(256) NOT NULL,
Road_Surface_Conditions VARCHAR(256) NOT NULL,
CONSTRAINT condition_pkey PRIMARY KEY(Condition_Index))
DISTSTYLE ALL;

CREATE TABLE IF NOT EXISTS public.local_authority (
LAD_Code VARCHAR(256) NOT NULL,
SubGroup VARCHAR(256) NOT NULL,
HighwayAuthority VARCHAR(256) NOT NULL,
SubGroup_Description VARCHAR(256) NOT NULL,
SuperGroup VARCHAR(256) NOT NULL,
Network_Density_Range VARCHAR(256) NOT NULL,
Urban_Road_Range VARCHAR(256) NOT NULL,
Region_Country VARCHAR(256) NOT NULL,
Geographical_Area VARCHAR(256) NOT NULL,
CONSTRAINT local_authority_pkey PRIMARY KEY(LAD_Code))
DISTSTYLE ALL;

CREATE TABLE IF NOT EXISTS public.time (
date_time TIMESTAMP NOT NULL,
Day_of_Week INTEGER NOT NULL,
week_of_year INTEGER NOT NULL,
week_of_month INTEGER NOT NULL,
Month INTEGER NOT NULL,
Year INTEGER NOT NULL,
CONSTRAINT time_pkey PRIMARY KEY(date_time))
DISTSTYLE ALL;

CREATE TABLE IF NOT EXISTS public.accident (
Accident_Index VARCHAR(256) NOT NULL,
LAD_Code VARCHAR(256) NOT NULL,
date_time TIMESTAMP NOT NULL,
Year INTEGER NOT NULL,
Police_Force INTEGER,
Accident_Severity INTEGER,
Number_of_Vehicles INTEGER,
Number_of_Casualties INTEGER,
first_Road_Number INTEGER,
Speed_limit INTEGER,
second_Road_Number INTEGER,
Urban_or_Rural_Area INTEGER,
Did_Police_Officer VARCHAR(256),
Condition_Index INTEGER,
Road_Index INTEGER,
Pedestrian_Index INTEGER)
DISTSTYLE ALL;